
#Directory Stucture for Makefile
#Plot Directory
#PFOLD = ~/Documents/Fluids/gaussian/plotData
#TFOLD = ~/Documents/Fluids/gaussian/plots
#Log File Directory
#LFOLD = ~/Documents/Fluids/gaussian/logs


FC = gfortran
#FFLAGS = -llapack -lblas
#What do LFLAGS do??????
#LFLAGS = -L/usr/local/lib -L/usr/lib

#Module File
#OMOD = gaussian_mod.o
#FMOD = ../src/gaussian_mod.f90

.PHONY : clean

addmats: addmats.e
		time ./$< >> exerciselog.txt

betteraddmats: betteraddmats.e
		time ./$< >> exerciselog.txt

%.e : %.o
		$(FC) -o $@ $< 

%.o : %.f90
		$(FC) -c $<

clean: 
		rm -rf *.e *.o


